package com.hospital.management.controller;

import com.hospital.management.dto.*;
import com.hospital.management.service.AppointmentService;
import com.hospital.management.service.DoctorService;
import com.hospital.management.service.PatientService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/admin")
@Tag(name = "Admin Operations", description = "Endpoints for administrator management including Doctors, Patients, Appointments, Analytics, and AI Logs")
public class AdminController {

    private final DoctorService doctorService;
    private final PatientService patientService;
    private final AppointmentService appointmentService;

    public AdminController(
            DoctorService doctorService,
            PatientService patientService,
            AppointmentService appointmentService) {
        this.doctorService = doctorService;
        this.patientService = patientService;
        this.appointmentService = appointmentService;
    }

    // --- DOCTOR CRUD ---

    @GetMapping("/doctors")
    @Operation(summary = "Get all doctors", description = "Retrieve list of all registered doctors (both active and inactive).")
    public ResponseEntity<List<DoctorDTO>> getAllDoctors() {
        return ResponseEntity.ok(doctorService.getAllDoctors());
    }

    @GetMapping("/doctors/{id}")
    @Operation(summary = "Get doctor by ID")
    @ApiResponse(responseCode = "200", description = "Doctor profile found")
    @ApiResponse(responseCode = "404", description = "Doctor profile not found")
    public ResponseEntity<DoctorDTO> getDoctorById(@PathVariable Long id) {
        return ResponseEntity.ok(doctorService.getDoctorById(id));
    }

    @PutMapping("/doctors/{id}")
    @Operation(summary = "Update doctor details")
    @ApiResponse(responseCode = "200", description = "Doctor updated successfully")
    @ApiResponse(responseCode = "404", description = "Doctor not found")
    public ResponseEntity<DoctorDTO> updateDoctor(@PathVariable Long id, @Valid @RequestBody DoctorDTO dto) {
        return ResponseEntity.ok(doctorService.updateDoctor(id, dto));
    }

    @DeleteMapping("/doctors/{id}")
    @Operation(summary = "Soft-delete doctor")
    @ApiResponse(responseCode = "204", description = "Doctor deactivated successfully")
    public ResponseEntity<Void> softDeleteDoctor(@PathVariable Long id) {
        doctorService.softDeleteDoctor(id);
        return ResponseEntity.noContent().build();
    }

    // --- PATIENT CRUD ---

    @GetMapping("/patients")
    @Operation(summary = "Get all patients")
    public ResponseEntity<List<PatientDTO>> getAllPatients() {
        return ResponseEntity.ok(patientService.getAllPatients());
    }

    @GetMapping("/patients/{id}")
    @Operation(summary = "Get patient by ID")
    public ResponseEntity<PatientDTO> getPatientById(@PathVariable Long id) {
        return ResponseEntity.ok(patientService.getPatientById(id));
    }

    @PutMapping("/patients/{id}")
    @Operation(summary = "Update patient details")
    public ResponseEntity<PatientDTO> updatePatient(@PathVariable Long id, @Valid @RequestBody PatientDTO dto) {
        return ResponseEntity.ok(patientService.updatePatient(id, dto));
    }

    @DeleteMapping("/patients/{id}")
    @Operation(summary = "Soft-delete patient")
    public ResponseEntity<Void> softDeletePatient(@PathVariable Long id) {
        patientService.softDeletePatient(id);
        return ResponseEntity.noContent().build();
    }

    // --- SYSTEM MONITORING & ANALYTICS ---

    @GetMapping("/appointments")
    @Operation(summary = "Get all appointments", description = "Retrieve a global history of appointments scheduled in the hospital.")
    public ResponseEntity<List<AppointmentDTO>> getAllAppointments() {
        return ResponseEntity.ok(appointmentService.getAllAppointments());
    }

    @GetMapping("/analytics")
    @Operation(summary = "Get system analytics", description = "Aggregates hospital metrics: total booking volume, cancellation percentages, and the busiest doctor specialties.")
    public ResponseEntity<Map<String, Object>> getAnalytics() {
        return ResponseEntity.ok(appointmentService.getAdminAnalytics());
    }

    @GetMapping("/ai-suggestions")
    @Operation(summary = "View AI Suggestion Audit Log", description = "Browse all past clinical symptom suggestions, diagnoses, and urgency levels generated by Gemini.")
    public ResponseEntity<List<AiSuggestionDTO>> getAiSuggestionsAuditLog() {
        return ResponseEntity.ok(appointmentService.getAiSuggestionsAuditLog());
    }
}
